"use client";

import { Shield, Sparkles, CheckCircle2, ListTodo, Bot, HelpCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 text-slate-900 space-y-12 bg-[#F8FAFC] min-h-screen">
      
      {/* Header */}
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold tracking-tight text-slate-950">
          How TrustLayer-AI Works
        </h1>
        <p className="text-sm text-slate-500 max-w-xl mx-auto font-medium">
          A deep dive into our explainable, citation-backed, and hallucination-free hotel recommendation engine.
        </p>
      </div>

      {/* RAG pipeline steps */}
      <div className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-sm space-y-8">
        <h2 className="text-xl font-extrabold text-slate-950 border-b border-slate-100 pb-3">
          Our Three Pillars of Explainable Travel AI
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Pillar 1 */}
          <div className="space-y-3">
            <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center">
              <Shield className="w-6 h-6 animate-pulse" />
            </div>
            <h3 className="font-bold text-slate-950 text-lg">100% Grounded Output</h3>
            <p className="text-xs text-slate-500 leading-relaxed">
              Every recommendation summaries are strictly verified against actual customer review snippets stored in our vector database. Any claim that cannot be proven is automatically omitted or remediated.
            </p>
          </div>

          {/* Pillar 2 */}
          <div className="space-y-3">
            <div className="w-12 h-12 rounded-xl bg-green-50 text-green-600 border border-green-100 flex items-center justify-center">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-slate-950 text-lg">Mathematical Aspect Scores</h3>
            <p className="text-xs text-slate-500 leading-relaxed">
              Aspect scores like Cleanliness, Service, Location, and Value are not generated by creative AI. They are mathematically compiled from thousands of reviews using deterministic sentiment scores.
            </p>
          </div>

          {/* Pillar 3 */}
          <div className="space-y-3">
            <div className="w-12 h-12 rounded-xl bg-orange-50 text-orange-600 border border-orange-100 flex items-center justify-center">
              <ListTodo className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-slate-950 text-lg">Drill-Down Provenance</h3>
            <p className="text-xs text-slate-500 leading-relaxed">
              We never ask you to take our AI's word for it. By expanding "View verification sources," you can audit the exact document chunks retrieved from ChromaDB that substantiate the AI's claims.
            </p>
          </div>
        </div>
      </div>

      {/* Math breakdown / Flow explanation */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        <div className="space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-950 tracking-tight">The Hybrid RAG Recommendation Cycle</h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            When you enter a specific prompt (e.g. <i>"family friendly hotels with clean rooms and high trust"</i>), the engine parses your constraints into hard areas and soft preferences.
          </p>
          <p className="text-xs text-slate-600 leading-relaxed">
            A hybrid retrieval queries ChromaDB, scoring candidate hotels by physical location match and sentiment alignment. Top candidates are compressed and sent to our local Ollama model to generate contextual match summaries.
          </p>
          <p className="text-xs text-slate-600 leading-relaxed">
            Finally, a strict citation injector verifies that references to cleanliness, staff, or value align with evidence, and a validation gate filters out hallucinated claims before the card displays on your screen.
          </p>
        </div>
        <div className="bg-slate-900 text-slate-300 p-6 rounded-2xl border border-slate-800 shadow-md space-y-4 font-mono text-xs">
          <div className="flex justify-between items-center text-blue-400 font-bold border-b border-slate-800 pb-2">
            <span>PIPELINE LOG TRACE</span>
            <span className="text-[10px] px-2 py-0.5 bg-blue-500/20 rounded-full border border-blue-500/30">AUDIT</span>
          </div>
          <p className="text-green-400">{"✓ QueryParser constraints: hard={'area': 'Delhi'}, soft={'family': True, 'clean': True}"}</p>
          <p className="text-slate-400">⚡ Retrieving from ChromaDB: Collection 'hotel_knowledge'...</p>
          <p className="text-slate-400">⚡ Running LLM summary: Prompt validation token limit 3000</p>
          <p className="text-green-400">✓ Citations mapped: Match reason verified against Chunk 12 & Chunk 15</p>
          <p className="text-blue-400">✓ Grounding score: 1.0 (Hallucination-free validation passed)</p>
        </div>
      </div>

      {/* CTA */}
      <div className="text-center pt-8 border-t border-slate-200">
        <Link href="/stays">
          <Button className="h-11 px-8 rounded-xl font-bold bg-blue-600 hover:bg-blue-500 text-white cursor-pointer shadow-md">
            Start Browsing Stays
          </Button>
        </Link>
      </div>

    </div>
  );
}
